### ISSUE TITLE
not working when run

### ISSUE THREAD

**Issue by fatin98-end** [mocha234/meritKeyIn_UMP#1]
C:\Users\Asus>pip install selenium
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\asus\appdata\roaming\python\python39\site-packages (4.0.0a7)
Requirement already satisfied: urllib3[secure] in c:\users\asus\appdata\roaming\python\python39\site-packages (from selenium) (1.26.2)
Requirement already satisfied: trio in c:\users\asus\appdata\roaming\python\python39\site-packages (from selenium) (0.18.0)
Requirement already satisfied: trio-websocket in c:\users\asus\appdata\roaming\python\python39\site-packages (from selenium) (0.9.1)
Requirement already satisfied: async-generator>=1.9 in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (20.3.0)
Requirement already satisfied: sniffio in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (2.3.0)
Requirement already satisfied: outcome in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (1.1.0)
Requirement already satisfied: idna in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio->selenium) (1.14.4)
Requirement already satisfied: pycparser in c:\users\asus\appdata\roaming\python\python39\site-packages (from cffi>=1.14->trio->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\appdata\roaming\python\python39\site-packages (from trio-websocket->selenium) (1.0.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\asus\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket->selenium) (0.12.0)
Requirement already satisfied: certifi in c:\users\asus\appdata\roaming\python\python39\site-packages (from urllib3[secure]->selenium) (2020.12.5)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\asus\appdata\roaming\python\python39\site-packages (from urllib3[secure]->selenium) (20.0.1)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\asus\appdata\roaming\python\python39\site-packages (from urllib3[secure]->selenium) (3.3.1)
Requirement already satisfied: six>=1.4.1 in c:\users\asus\appdata\roaming\python\python39\site-packages (from cryptography>=1.3.4->urllib3[secure]->selenium) (1.15.0)

C:\Users\Asus>cd "C:\Users\Asus\Desktop\CLUB CHEST 20_21\MERIT\meritKeyIn_UMP-master"

C:\Users\Asus\Desktop\CLUB CHEST 20_21\MERIT\meritKeyIn_UMP-master>python meritKeyIn_for_IEM.py

        +-----------------------------------------------------------------------------+
        |            ====     ====  ======  ========    =======  =======              |
        |            == ==   == ==  ==      ==     ==     ==       ==                 |
        |            == ==   == ==  ======  ==     ==     ==       ==                 |
        |            ==  == ==  ==  ==      ==  ===       ==       ==                 |
        |            ==   ===   ==  ======  ==     ===  =======    ==   KeyInMadeEasy |
        |                                                                             |
        | Written by mocha234, for any inquiry, please reach out to me @              |
        |                   github.com/mocha234                                       |
        +-----------------------------------------------------------------------------+

        Secretary's Matric ID:
        Password: 

        Since there's no error for wrong password checking, please check if it's correct:
        Secretary's Matric ID: 
        Password: 

        Proceed? (y/n):y

        Event's Merit Fill-In page's link:

        https://std-comm.ump.edu.my/ecommstudent/application_activities.jsp?action=UniversityCommiteeAdd&caa_ref_id=2020036541

        Dual check please? :)
        Link: https://std-comm.ump.edu.my/ecommstudent/application_activities.jsp?action=UniversityCommiteeAdd&caa_ref_id=2020036541

        Proceed? (y/n):y

        Checklist:

        Please ensure these following are ready, to avoid 'stuck'

         ---> 1. Replace the matricID.csv?

         ---> 2. matricID.csv only contain one column starting from row 0

                 with students' matric ID?

         ---> 3. Data preprocessed? Only Local students' in the .csv file

        Proceed? (y/n):y

DevTools listening on ws://127.0.0.1:50319/devtools/browser/8cca0230-3af9-4b8a-a62a-528b32224784
C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py:451: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
[6184:2788:0116/204025.054:ERROR:device_event_log_impl.cc(211)] [20:40:25.054] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\CLUB CHEST 20_21\MERIT\meritKeyIn_UMP-master\meritKeyIn_for_IEM.py", line 102, in <module>
    browser.find_element_by_xpath(modalButton).click()
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 452, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 1138, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 368, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 240, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="myModal"]/div/div/div[3]/button"}
  (Session info: chrome=87.0.4280.141)
Stacktrace:
Backtrace:
        Ordinal0 [0x009DC0C3+3326147]
        Ordinal0 [0x008C0851+2164817]
        Ordinal0 [0x00747298+619160]
        Ordinal0 [0x006CC070+114800]
        Ordinal0 [0x006EFC42+261186]
        Ordinal0 [0x006E1A2A+203306]
        Ordinal0 [0x006EE559+255321]
        Ordinal0 [0x006E189B+202907]
        Ordinal0 [0x006C3DF4+81396]
        Ordinal0 [0x006C4DEE+85486]
        Ordinal0 [0x006C4D79+85369]
        Ordinal0 [0x008D85DC+2262492]
        GetHandleVerifier [0x00B62874+1487204]
        GetHandleVerifier [0x00B623CD+1486013]
        GetHandleVerifier [0x00B6A368+1518680]
        GetHandleVerifier [0x00B62F4E+1488958]
        Ordinal0 [0x008CED0D+2223373]
        Ordinal0 [0x008DA12B+2269483]
        Ordinal0 [0x008DA26F+2269807]
        Ordinal0 [0x008EECB8+2354360]
        BaseThreadInitThunk [0x7583FA29+25]
        RtlGetAppContainerNamedObjectPath [0x774B75F4+228]
        RtlGetAppContainerNamedObjectPath [0x774B75C4+180]

**Comment by mocha234** [comment]
E-Comm update, where no pop-out. Omitted the click "close pop-out" and redirect back to add names page.

New file uploaded. The changelog can be found here: https://github.com/mocha234/meritKeyIn_UMP/blob/master/Changelog.md

Thanks for noticing it!!
